name: Development

on:
  push:
    branches:
      - develop

jobs:
  heroku-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Disable Husky
        run: rm -rf .husky

      - name: Install Dependencies
        run: npm install --omit=dev --ignore-scripts
        
      - name: Cleanup
        run: rm -rf tests/ large-assets/

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_DEV_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
